---
name: SunAccessManagerSettings
version: 3
class: com.vordel.circuit.sun.SunAccessManagerSettings
fields:
  com.iplanet.services.debug.level:
    type: string
    defaultValues:
    - data: message
    cardinality: 1
  com.iplanet.services.debug.directory:
    type: string
    defaultValues:
    - data: suntrace
    cardinality: 1
  com.iplanet.am.naming.url:
    type: string
    defaultValues:
    - data: http://access-manager:8080/amserver/namingservice
    cardinality: 1
  com.sun.identity.agents.app.username:
    type: string
    defaultValues:
    - data: admin
    cardinality: 1
  com.iplanet.am.service.password:
    type: encrypted
    defaultValues:
    - {}
    cardinality: 1
  com.sun.identity.agents.server.log.file.name:
    type: string
    defaultValues:
    - data: amRemotePolicyLog
    cardinality: 1
  com.sun.identity.agents.logging.level:
    type: string
    defaultValues:
    - data: NONE
    cardinality: 1
  com.sun.identity.sm.cacheTime:
    type: string
    defaultValues:
    - data: 1
    cardinality: 1
  com.sun.identity.agents.polling.interval:
    type: string
    defaultValues:
    - data: 3
    cardinality: 1
components:
  Property: '*'
loadorder: 400
