---
certificates:
  example-server:
    provider: keystore
    config:
      path: ../all/ops-keystore.jks
      pass: "{{ keepass('/prod/ops-keystore:password') }}"
      alias: prod-axway-server
      
  example-root-ca:
    provider: keystore
    config:
      path: ../all/ops-keystore.jks
      pass: "{{ keepass('/prod/ops-keystore:password') }}"
      alias: demo-axway-root-ca

  example-sub-ca:
    provider: keystore
    config:
      path: ../all/ops-keystore.jks
      pass: "{{ keepass('/prod/ops-keystore:password') }}"
      alias: demo-axway-sub-ca

  # Remove test certificate
  acme:
    provider: remover
...
