# All values for which Ops is responsible for
Server_Settings:
  Cassandra_Settings:
    username: "{{ _ops_kdb('/prod/Cassandra', 'user') }}"
    password: "{{ _ops_kdb('/prod/Cassandra', 'password') | base64encode }}"
