= FAQ
:Author: Martin Look
:Email: mlook@axway.com
:source-highlighter: prettify
ifdef::env-github[]
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


== Security

=== There is a CVE-2022-37767 for Pebble Templates, is _YAML-ES Utilities_ affected?

According to CVE-2022-37767 any Java method could be executed by a Pebble template.

In the example below, the `toString()` method of the String object can be invoked within a Pebble template.

[source]
----
{% set value=\"Hello\".toString() %}{{ value }}
----

The _Pebble Templates_ engine within the _YAML-ES Utilities_ is configured to reject the invocation of a any Java method.
Therefore, the example above will throw an exception.

So, _YAML-ES Utilities_ is not affected by CVE-2022-37767.

== Usage

=== How do I add values with YAML style configuration to `values.yaml`?

Within the `values.yaml` file of the YAML entity store, several options exists to https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_yamles/yamles_environmentalization/index.html[configure] the API Gateway at runtime.

The YAML style options also uses the `{{ ... }}` syntax, which is the same syntax as for the Mustache templates used by _YAML-ES Utilities_.

If values in the configuration fragments, uses values in the YAML style, they are treated as Mustache templates and will be lead to a syntax error or will be replaced.

To force the output of the YAML style, the values must be specified as Mustache template having a string literal.

.Configuration Fragment
[source, yaml]
----
account:
  password: '{{ "{{env ACCOUNT_PASSWORD }}" }}'
----

.Generated `values.yaml`
[source, yaml]
----
account:
  password: {{env ACCOUNT_PASSWORD }}
----


== Contribution

=== I found a bug, what shall I do?

If you find a bug, don't hesitate to open an issue on the GitHub project page.
I'll try to help you as soon as possible.

[NOTE]
====
Please remember, it is a community project.
The plugin isn't officially supported by Axway.
So, please *don't* open a case in the Axway support portal.
====

=== I have a great idea to improve the plugin, what shall I do?

Feedback is always appreciated.
So open an issue on the GitHub project and describe your ideas.

== Documentation

=== What about the `.adoc` extension?

The documentation is written in Asciidoc.
So we use the extension `.adoc` for documentation files.

=== How can I read the documentation of the cloned repository in a nice format?

There is an _Asciidoctor.js_ extension for Chrome to view Asciidoc files in a beautiful format.

=== How do I get the documentation in PDF format?

link:https://asciidoctor.org/[Asciidoctor] provides some tools to render Asciidoc sources into various output formats.
link:https://github.com/asciidoctor/asciidoctor-pdf[Asciidoctor PDF] can be used to convert the documentation into a well layouted PDF document.
Follow the instructions on the the home page to install the tool.

To generate the PDF execute the following command in the root project folder:

[source,shell]
----
$ asciidoctor-pdf -a pdf-themesdir=docs/pdf-themes -a pdf-theme=axway docs/asciidoc/user-guide.adoc -d book -o user-guide.pdf
----
