= Templates
ifdef::env-github[]
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
ifndef::imagesdir[:imagesdir: ./images]

== Mustache Templates

The values of configuration fragments are treated as _Mustache_ templates.
After all configuration fragments are merged, the values will be evaluated by a template engine.
Values containing `{{ ... }}` statements are handled as templates, and are processed by the built-in template engine, before the resulting `values.yaml` file is written.

NOTE: The name _Mustache_ is derived from the used `{` characters, which resemble a sideways moustache.

_YAML-ES Utilities_ use link:https://pebbletemplates.io/[Pebble Templates] as the internal template engine.
All functions provided by this engine can also be used within the _Mustache_ templates.
Additionally to the functions provided by the template engine, custom lookup functions can be defined to lookup values from external sources.

Please consult the link:https://pebbletemplates.io/[Pebble documentation] for the syntax of templates and the capabilities provided by Pebble.

[IMPORTANT]
====
Each value of the configuration fragments or configuration parameters, are handled as a separate template.
So it's not possible to use templates outside or across properties.

.Invalid Configuration Fragment
[source, yaml]
----
db:
  user: "{{ _env('USER_NAME') }}" #<1>
  {{ 'password: "changeme"' }} #<2>
----
<1> Templates within properties are allowed
<2> Templates outside of properties are *not* supported
====

[NOTE]
====
For the _Pebble Templates_ engine a CVE-2022-37767 exists.
According to the CVE any arbitrary Java method can be invoked by the templates.

The _Pebble Templates_ engine within _YAML-ES Utilities_ is configured to prevent the call of Java method.
No Java method can be called within the templates.
So, the example below will throw an exception.

[source]
----
{% set value=\"Hello\".toString() %}{{ value }}
----

Therefore, _YAML-ES Utilities_ is not vulnerable by CVE-2022-37767.

As reported CVEs may be an issue in the context of an enterprise, even if the tool is not affected, the _Pebble Templates_ engine may be replaced in the future.
====

== Lookup Functions

Lookup functions can be used inside <<Mustache Templates>>, and are used to retrieve values from external sources.
To avoid any conflict with Pebble functions, all lookup function names start with an underscore.

Arguments are passed as positional or named arguments.
For positional arguments, the arguments must match the documented/expected order of the lookup function arguments.
For named arguments, the order of the arguments doesn't matter.

.Named Arguments
[source]
----
{{ _function(key="test", option="opt") }}
----

.Positional Arguments
[source]
----
{{ _function("test", "opt") }}
----

Lookup functions are implemented by, so called, _Lookup Providers_.

Built-in lookup functions are available without any additional configuration.
The name of the built-in lookup function is fixed and defined by the _Lookup Provider_ implementing the function.

For example, the <<Core>> plugin provides the following built-in lookup functions:

* `_env("env_name")`: Lookup values from an environment variable.
* `_sys("prop_name")`: Lookup values from system properties.

Other lookup functions can be dynamically configured via _lookup function configuration_ files.
Within these files, aliases for the lookup sources are defined.
The lookup sources are configured via a parameterized lookup provider (see <<Plugins>> for a list of lookup providers implemented by the according plugin).
For each alias a lookup function will be registered.
The name of the function is derived from the alias name by adding an underscore.

Aliases must be unique over all function configurations.
As the `env` and `sys` alias is already used by the built-in functions, these aliases are not allowed for custom lookup functions.

.Lookup Functions Configuration
[source, yaml]
----
lookups: #<1>
  dev_kdb: #<2>
    provider: keepass #<3>
    config: #<4>
      kdb: "../all/lookups/devs-secrets.kdbx" #<5>
      passphrase: "{{ _env('ENV_KDB_PASSPHRASE') }}" #<6>
----
<1> Root object for lookup definitions.
<2> Alias of the lookup function.
The name of lookup function is prefixed with a `_` (e.g. `_dev_kdb`). 
Aliases must be unique within all applied lookup provider configurations.
<3> Lookup provider used by the function.
<4> Configuration parameters for the lookup provider.
<5> Fixed configuration parameter.
<6> Configuration parameters retrieved via lookup function (only built-in functions supported).

[NOTE]
====
The _YAML-ES Utilities_ provide list of available lookup functions with the following command.
To list all functions as used for the merge command, the _lookup function configuration_ files can be specified in the same way as for the merge command.
If the missing, only the built-in functions are listed.

[source, shell]
----
$ yamlesutils merge [--lookup-functions=FILE]... describe functions
----
====
