---
type: FilterCircuit
fields:
  start: ./Set Attribute Filter
  name: Approve Application Registration
  description: When a new Application has been registered but approval is needed (only if auto-approved disabled)
  category: /System/Policy Categories/management
children:
- type: SetAttributeFilter
  fields:
    messageAttribute: alert.message
    attributeValue: Registration of application ${alert.application.name} has been approved.
    name: Set Attribute Filter
  routing:
    success: ../Call 'Send Alert'
  logging:
    fatal: 'Error while setting the attribute value. Error: ${circuit.exception}'
    failure: Failed to set the attribute value
    success: Set the attribute value
- type: CircuitDelegateFilter
  fields:
    circuitPK: /Policies/Sample Policies/API Management Alerts/Send Alert
    name: Call 'Send Alert'
  logging:
    fatal: 'Error in calling policy shortcut circuit. Error: ${circuit.exception}'
    failure: Failed in calling policy shortcut
    success: Success in calling policy shortcut
