---
External_Connections:
  Database_Connections:
    Masterdata:
      url: '{{ _dev_kdb("/Database/prod/MasterData", "url") }}'
      username: '{{ _dev_kdb("/Database/prod/MasterData", "user") }}'
      password: '{{ _dev_kdb("/Database/prod/MasterData", "password") | base64encode }}'

Policies:
  Demo:
    Demo_Service:
      Set_name:
        attributeValue: Prod Developer
      Feature_toggle:
        attributeValue: "false"
