---
External_Connections:
  Database_Connections:
    Masterdata:
      url: '{{ yaml("/db/masterdata/url") }}'
      username: '{{ yaml("/db/masterdata/user") }}'
      password: '{{ yaml("/db/masterdata/password") | base64encode }}'

Policies:
  Demo:
    Demo_Service:
      Set_name:
        attributeValue: Local Developer
      Feature_toggle:
        attributeValue: "true"

