---
Server_Settings:
  Cassandra_Settings:
    replicationStrategy: '{{ _lookup("/cassandra/replication/strategy") }}'
    replication: '{{ _lookup("/cassandra/replication/factor") }}'
    throttlingReplicationStrategy: '{{ _lookup("/cassandra/replication/strategy") }}'
    throttlingReplication: '{{ _lookup("/cassandra/replication/factor") }}'
    throttlingReadConsistencyLevel: '{{ _lookup("/cassandra/consistency/read") }}'
    throttlingWriteConsistencyLevel: '{{ _lookup("/cassandra/consistency/write") }}'
    username: '{{ _lookup("/cassandra/security/username") }}'
    password: '{{ _lookup("/cassandra/security/password") | base64encode }}'
    useSSL: '{{ _lookup("/cassandra/security/ssl_enabled") }}'

Environment_Configuration:
  Key_Property_Stores:
    API_Portal:
      Data_Sources:
        Cassandra_Storage:
          readConsistencyLevel: '{{ _lookup("/cassandra/consistency/read") }}'
          writeConsistencyLevel: '{{ _lookup("/cassandra/consistency/write") }}'
    API_Server:
      Data_Sources:
        Cassandra_Storage:
          readConsistencyLevel: '{{ _lookup("/cassandra/consistency/read") }}'
          writeConsistencyLevel: '{{ _lookup("/cassandra/consistency/write") }}'
    OAuth:
      DataSources:
        Cassandra_Storage:
          readConsistencyLevel: '{{ _lookup("/cassandra/consistency/read") }}'
          writeConsistencyLevel: '{{ _lookup("/cassandra/consistency/write") }}'

External_Connections:
  Database_Connections:
    Default_Database_Connection:
      url: '{{ _lookup("/db/metrics/url") }}'
      username: '{{ _lookup("/db/metrics/user") }}'
      password: '{{ _lookup("/db/metrics/password") | base64encode }}'
