---
# All values for which Ops is responsible for
Server_Settings:
  Cassandra_Settings:
    replicationStrategy: '{{ _ops_yfile("/cassandra/replication/strategy") }}'
    replication: '{{ _ops_yfile("/cassandra/replication/factor") }}'
    throttlingReplicationStrategy: '{{ _ops_yfile("/cassandra/replication/strategy") }}'
    throttlingReplication: '{{ _ops_yfile("/cassandra/replication/factor") }}'
    throttlingReadConsistencyLevel: '{{ _ops_yfile("/cassandra/consistency/read") }}'
    throttlingWriteConsistencyLevel: '{{ _ops_yfile("/cassandra/consistency/write") }}'
    useSSL: '{{ _ops_yfile("/cassandra/security/ssl_enabled") }}'
Environment_Configuration:
  Key_Property_Stores:
    API_Portal:
      Data_Sources:
        Cassandra_Storage:
          readConsistencyLevel: '{{ _ops_yfile("/cassandra/consistency/read") }}'
          writeConsistencyLevel: '{{ _ops_yfile("/cassandra/consistency/write") }}'
    API_Server:
      Data_Sources:
        Cassandra_Storage:
          readConsistencyLevel: '{{ _ops_yfile("/cassandra/consistency/read") }}'
          writeConsistencyLevel: '{{ _ops_yfile("/cassandra/consistency/write") }}'
    OAuth:
      DataSources:
        Cassandra_Storage:
          readConsistencyLevel: '{{ _ops_yfile("/cassandra/consistency/read") }}'
          writeConsistencyLevel: '{{ _ops_yfile("/cassandra/consistency/write") }}'
External_Connections:
  Database_Connections:
    Default_Database_Connection:
      url: '{{ _ops_jfile("/db/metrics/url") }}'
      username: '{{ _env("DB_METRICS_USER") }}'
      password: '{{ _ops_jenv("/db/metrics/password") | base64encode }}'
