---
name: EnvironmentalizedFieldBoolean
version: 0
class: com.vordel.api.deployment.model.EnvironmentalizedFieldBoolean
fields:
  value:
    type: boolean
    defaultValues:
    - {}
    cardinality: '?'
