---
type: FilterCircuit
fields:
  start: ./Set Attribute Filter
  name: Application Quota Exceeded
  description: An application quota is exceeded
children:
- type: SetAttributeFilter
  fields:
    messageAttribute: alert.message
    attributeValue: 'Error: usage of API ${api.name}, operation ${api.method.name} by application ${authentication.subject.id} has exceeded APPLICATION Quota.'
    name: Set Attribute Filter
  routing:
    success: ../Call 'Send Alert'
  logging:
    fatal: 'Error while setting the attribute value. Error: ${circuit.exception}'
    failure: Failed to set the attribute value
    success: Set the attribute value
- type: CircuitDelegateFilter
  fields:
    circuitPK: /Policies/Sample Policies/API Management Alerts/Send Alert
    name: Call 'Send Alert'
  logging:
    fatal: 'Error in calling policy shortcut circuit. Error: ${circuit.exception}'
    failure: Failed in calling policy shortcut
    success: Success in calling policy shortcut
