---
type: FilterCircuit
fields:
  start: ./Switch on Attribute Value
  name: Create Application Credential
  description: An Application Credential is created
children:
- type: SwitchFilter
  fields:
    attributeName: ${alert.appcredential.type}
    defaultOption: RETURN_TRUE
    defaultCircuit: /null
    name: Switch on Attribute Value
  children:
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: external
      name: Id-0001523272943702-0000000062c23855-1
      priority: 2
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/External/External Credential Created
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: oauth
      name: Id-0001523272914344-0000000032813174-1
      priority: 1
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/OAuth/OAuth Credential Created
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: apikey
      name: Id-0001522831264414-ffffffffb008fcdd-1
      priority: 0
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/APIKey/APIKey Created
