---
type: FilterCircuit
fields:
  start: ./Switch on Attribute Value
  name: Delete Application Credential
  description: An Application Credential is deleted
children:
- type: SwitchFilter
  fields:
    attributeName: ${alert.appcredential.type}
    defaultOption: RETURN_TRUE
    defaultCircuit: /null
    name: Switch on Attribute Value
  children:
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: oauth
      name: Id-0001523285769171-ffffffffe3bf4ce0-1
      priority: 1
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/OAuth/OAuth Credential Deleted
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: external
      name: Id-0001523285812848-ffffffff80fb952d-1
      priority: 2
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/External/External Credential Deleted
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: apikey
      name: Id-0001522831264414-ffffffffb008fcdd-1
      priority: 0
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/APIKey/APIKey Deleted
