---
type: FilterCircuit
fields:
  start: ./Switch on Attribute Value
  name: Disable Application Credential
  description: An Application Credential is disabled
children:
- type: SwitchFilter
  fields:
    attributeName: ${alert.appcredential.type}
    defaultOption: RETURN_TRUE
    defaultCircuit: /null
    name: Switch on Attribute Value
  children:
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: apikey
      name: Id-0001522831264414-ffffffffb008fcdd-1
      priority: 0
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/APIKey/APIKey Disabled
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: external
      name: Id-0001523285873228-ffffffffb9a029e0-1
      priority: 2
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/External/External Credential Disabled
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: oauth
      name: Id-0001523285845902-000000001ebe24e4-1
      priority: 1
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/OAuth/OAuth Credential Disabled
