---
type: FilterCircuit
fields:
  start: ./Switch on Attribute Value
  name: Enable Application Credential
  description: An Application Credential is enabled
children:
- type: SwitchFilter
  fields:
    attributeName: ${alert.appcredential.type}
    defaultOption: RETURN_TRUE
    defaultCircuit: /null
    name: Switch on Attribute Value
  children:
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: external
      name: Id-0001523285931885-0000000032030c35-1
      priority: 2
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/External/External Credential Enabled
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: apikey
      name: Id-0001522831264414-ffffffffb008fcdd-1
      priority: 0
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/APIKey/APIKey Enabled
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: oauth
      name: Id-0001523285909226-000000000d542e78-1
      priority: 1
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/OAuth/OAuth Credential Enabled
