---
type: FilterCircuit
fields:
  start: ./Switch on Attribute Value
  name: Update Application Credential
  description: An Application Credential is updated
children:
- type: SwitchFilter
  fields:
    attributeName: ${alert.appcredential.type}
    defaultOption: RETURN_TRUE
    defaultCircuit: /null
    name: Switch on Attribute Value
  children:
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: apikey
      name: Id-0001522831264414-ffffffffb008fcdd-1
      priority: 0
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/APIKey/APIKey Updated
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: oauth
      name: Id-0001523285969406-000000005b72e6cb-1
      priority: 1
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/OAuth/OAuth Credential Updated
  - type: SwitchCircuitReference
    fields:
      comparatorType: is
      compareWith: external
      name: Id-0001523285988807-000000004169ae6b-1
      priority: 2
      circuitPK: /Policies/Sample Policies/API Management Alerts/Application Credentials/External/External Credential Updated
