---
type: PortalCallback
fields:
  name: Reset Application Developer Password
  id: alert.appdev.resetpwd
  type: Governance
  enabled: true
  filterCircuit: /Policies/Sample Policies/API Management Alerts/Application Developer/Reset Application Developer Password
