= FAQ
:Author: Martin Look
:Email: mlook@axway.com
:source-highlighter: prettify
ifdef::env-github[]
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


== Contribution

=== I found a bug, what shall I do?

If you find a bug, don't hesitate to open an issue on the GitHub project page.
I'll try to help you as soon as possible.

[NOTE]
====
Please remember, it is a community project.
The plugin isn't officially supported by Axway.
So, please *don't* open a case in the Axway support portal.
====

=== I have a great idea to improve the plugin, what shall I do?

Feedback is always appreciated.
So open an issue on the GitHub project and describe your ideas.

== Features


== Documentation

=== What about the `.adoc` extension?

The documentation is written in Asciidoc.
So we use the extension `.adoc` for documentation files.

=== How can I read the documentation of the cloned repository in a nice format?

There is an _Asciidoctor.js_ extension for Chrome to view Asciidoc files in a beautiful format.

=== How do I get the documentation in PDF format?

link:https://asciidoctor.org/[Asciidoctor] provides some tools to render Asciidoc sources into various output formats.
link:https://github.com/asciidoctor/asciidoctor-pdf[Asciidoctor PDF] can be used to convert the documentation into a well layouted PDF document.
Follow the instructions on the the home page to install the tool.

To generate the PDF execute the following command in the root project folder:

[source,shell]
----
  $ asciidoctor-pdf -a pdf-themesdir=doc/pdf-themes -a pdf-theme=axway doc/manual/user-guide.adoc -d book -o user-guide.pdf
----
