---
name: PortalApplicationCredentialReadFilter
version: 0
class: com.vordel.circuit.apiportal.ReadApplicationCredentialFilter
fields:
  credentialType:
    type: string
    defaultValues:
    - data: apikey
    cardinality: 1
  idSelector:
    type: string
    defaultValues:
    - data: ${apimgmt.appcredential.id}
    cardinality: 1
  targetAttribute:
    type: string
    defaultValues:
    - data: apimgmt.appcredential
    cardinality: 1
