---
type: XMLFirewall
fields:
  filterCircuit: /Policies/OAuth 2.0/Authorization Service/Client Application Logo
  uriprefix: /api/oauth/application/image/
children:
- type: PortableCircuitReference
  fields:
    circuitPK: /null
    name: CUSTOM_POLICY_RSP
    priority: 3
- type: PortableCircuitReference
  fields:
    circuitPK: /null
    name: CUSTOM_POLICY_REQ
    priority: 1
- type: SoftCircuitReference
  fields:
    circuitPK: system.policy.response
    name: GLOBAL_POLICY_RSP
    priority: 4
- type: SoftCircuitReference
  fields:
    circuitPK: system.policy.request
    name: GLOBAL_POLICY_REQ
    priority: 0
