---
type: PortalCallback
fields:
  name: Approve Application API Access
  id: alert.application.approveapi
  type: Governance
  enabled: true
  filterCircuit: /Policies/Sample Policies/API Management Alerts/Application/Approve Application API Access
