---
type: KPSType
fields:
  name: PortalApplications
  description: Portal applications
children:
- type: KPSTypeProperty
  fields:
    name: tags
    type: java.util.Map
    key: java.lang.String
    value: java.lang.String
- type: KPSTypeProperty
  fields:
    name: email
    type: java.lang.String
- type: KPSTypeProperty
  fields:
    name: organizationId
    type: java.lang.String
- type: KPSTypeProperty
  fields:
    name: id
    type: java.lang.String
- type: KPSTypeProperty
  fields:
    name: image
    type: java.lang.String
- type: KPSTypeProperty
  fields:
    name: description
    type: java.lang.String
- type: KPSTypeProperty
  fields:
    name: enabled
    type: java.lang.Boolean
- type: KPSTypeProperty
  fields:
    name: createdOn
    type: java.lang.Long
- type: KPSTypeProperty
  fields:
    name: phone
    type: java.lang.String
- type: KPSTypeProperty
  fields:
    name: name
    type: java.lang.String
- type: KPSTypeProperty
  fields:
    name: quotaId
    type: java.lang.String
- type: KPSTypeProperty
  fields:
    name: createdBy
    type: java.lang.String
