---
type: PortalCallback
fields:
  name: Create Application Credential
  id: alert.applicationcredentials.create
  type: Governance
  enabled: true
  filterCircuit: /Policies/Sample Policies/API Management Alerts/Application Credentials/Create Application Credential
