---
type: PortalCallback
fields:
  name: Delete Application Credential
  id: alert.applicationcredentials.delete
  type: Governance
  enabled: true
  filterCircuit: /Policies/Sample Policies/API Management Alerts/Application Credentials/Delete Application Credential
