---
type: PortalCallback
fields:
  name: Disable Application Credential
  id: alert.applicationcredentials.disable
  type: Governance
  enabled: true
  filterCircuit: /Policies/Sample Policies/API Management Alerts/Application Credentials/Disable Application Credential
