---
type: PortalCallback
fields:
  name: Enable Application Credential
  id: alert.applicationcredentials.enable
  type: Governance
  enabled: true
  filterCircuit: /Policies/Sample Policies/API Management Alerts/Application Credentials/Enable Application Credential
